name: Vercel CI/CD
description: Build & Deploy to Vercel
author: Pablo Cru Delhom (pabcrudel)

inputs:
  environment:
    description: Which environment should be used
    required: false
    default: preview
  vercel_token:
    description: Secret token to communicate with Vercel
    required: true

runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Pull Vercel Environment Information
      shell: bash
      run: |
        vercel pull --yes\
        --environment=${{ inputs.environment }}\
        --token=${{ inputs.vercel_token }}

    - name: Initialize Prisma client
      shell: bash
      run: pnpm prisma generate

    - name: Build & Deploy Project Artifacts to Vercel
      shell: bash
      run: |
        # "production" must be specified
        if [[ ${{ inputs.environment }} == 'production' ]]; then
          vercel build --prod --token=${{ inputs.vercel_token }};
          vercel deploy --prebuilt --prod --token=${{ inputs.vercel_token }};
        else
          vercel build --token=${{ inputs.vercel_token }};
          vercel deploy --prebuilt --token=${{ inputs.vercel_token }};
        fi
