# Source https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Build & Deploy to Vercel
        uses: ./.github/actions/vercel-ci-cd
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
