# Source https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: Vercel Preview Deployment

on:
  workflow_dispatch:

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Build & Deploy to Vercel
        uses: ./.github/actions/vercel-ci-cd
